eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
---
spring:
  profiles: production
  
---
spring:
  profiles: development
